command: ['streamlit', 'run', 'app.py']
env:
  - name: DATABRICKS_HOST
    value: 'dbc-b8c7c49e-9e63.cloud.databricks.com'
  - name: DATABRICKS_HTTP_PATH
    value: '/sql/1.0/warehouses/0dfb28cd62b755d9'
  - name: DATABRICKS_TOKEN
    value: 'dapid21506aed4b53a4caa9cc7a752a2bb54'
  - name: GEMINI_API_KEY
    valueFrom: GEMINI_API_KEY
